import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Banner from "../components/banner/banner";
import Card from "../components/card/card";
import coffeeStores from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  const data = coffeeStores;
  return {
    props: {
      data,
    }, //will be passed to the page component as props
  };
}

export default function Home(props) {
  console.log(props);
  function handleOnBannerBtnClick() {
    console.log("Click");
  }
  /*   const name = "Coffee Shop";
  const href = "Dynamic Shop";
  const imageUrl = "/static/coffee-shop.jpeg"; 
  console.log("styles on home", styles.container); */
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Shop Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>
        <div className={styles.cardLayout}>
          {/*           <h2>Stores near me</h2>
           */}{" "}
          {props.data.map((coffeeStores, i) => {
            return (
              <Card
                key={props.data[i].id}
                className={styles.card}
                name={props.data[i].name}
                href={`${props.data[i].id}`}
                imageUrl={props.data[i].imgUrl}
              />
            );
          })}
        </div>
        <div>{console.log(props.data[0])}</div>
      </main>
    </div>
  );
}
